let purchases = [
  {
    serialNumber: 1,
    insuranceName:
      "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.",
    companyName: "Nienow, Lebsack and Pouros",
    insuranceType: "Health Insurance",
    price: 357.4,
    purchasedOn: "5/30/2020",
    fullName: "Orelee Mellhuish",
    passportNumber: 85114,
    age: 30,
    mobileNumber: "886 768 9611",
    gender: "Female",
    streetName: "Milwaukee",
    buildingNumber: "9064",
    apartmentNumber: "6",
    postCode: "5312",
    city: "Quezon City",
    region: "Philippines",
  },
  {
    serialNumber: 2,
    insuranceName:
      "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    companyName: "Lubowitz, Franecki and Jerde",
    insuranceType: "Travel Insurance",
    price: 535.77,
    purchasedOn: "6/28/2020",
    fullName: "Denis Bridgewood",
    passportNumber: 21502,
    age: 5,
    mobileNumber: "855 855 3880",
    gender: "Male",
    streetName: "Union",
    buildingNumber: "58",
    apartmentNumber: "923",
    postCode: "1049",
    city: "Amsterdam Westpoort",
    region: "Netherlands",
  },
  {
    serialNumber: 3,
    insuranceName:
      "Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    companyName: "Marvin-Macejkovic",
    insuranceType: "Life Insurance",
    price: 266.09,
    purchasedOn: "4/29/2020",
    fullName: "Ernestus Edmondson",
    passportNumber: 53664,
    age: 66,
    mobileNumber: "526 785 0002",
    gender: "Male",
    streetName: "Mcbride",
    buildingNumber: "38",
    apartmentNumber: "2",
    postCode: "2409",
    city: "Alphen aan den Rijn",
    region: "Netherlands",
  },
];

module.exports = purchases;
