// GUEST ACTIONS
export const GET_INSURANCES_LOADING = "GET_INSURANCES_LOADING";
export const GET_INSURANCES_SUCCESS = "GET_INSURANCES_SUCCESS";
export const GET_INSURANCES_ERROR = "GET_INSURANCES_ERROR";

// SHARED ACTIONS FOR - USER, ADMIN
export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

// USER ACTIONS
export const GET_PREVIOUS_PURCHASES_LOADING = "GET_PREVIOUS_PURCHASES_LOADING";
export const GET_PREVIOUS_PURCHASES_SUCCESS = "GET_PREVIOUS_PURCHASES_SUCCESS";
export const GET_PREVIOUS_PURCHASES_ERROR = "GET_PREVIOUS_PURCHASES_ERROR";

export const BUY_INSURANCE_LOADING = "BUY_INSURANCE_LOADING";
export const BUY_INSURANCE_SUCCESS = "BUY_INSURANCE_SUCCESS";
export const BUY_INSURANCE_ERROR = "BUY_INSURANCE_ERROR";

// ADMIN ACTIONS
export const GET_INSURANCES_LIST_LOADING = "GET_INSURANCES_LIST_LOADING";
export const GET_INSURANCES_LIST_SUCCESS = "GET_INSURANCES_LIST_SUCCESS";
export const GET_INSURANCES_LIST_ERROR = "GET_INSURANCES_LIST_ERROR";

export const ADD_INSURANCE_LOADING = "ADD_INSURANCE_LOADING";
export const ADD_INSURANCE_SUCCESS = "ADD_INSURANCE_SUCCESS";
export const ADD_INSURANCE_ERROR = "ADD_INSURANCE_ERROR";

export const UPDATE_INSURANCE_LOADING = "UPDATE_INSURANCE_LOADING";
export const UPDATE_INSURANCE_SUCCESS = "UPDATE_INSURANCE_SUCCESS";
export const UPDATE_INSURANCE_ERROR = "UPDATE_INSURANCE_ERROR";

export const DELETE_INSURANCE_LOADING = "DELETE_INSURANCE_LOADING";
export const DELETE_INSURANCE_SUCCESS = "DELETE_INSURANCE_SUCCESS";
export const DELETE_INSURANCE_ERROR = "DELETE_INSURANCE_ERROR";

// CART ACTIONS
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
